(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"ScalarTest",
  Authors -> {"Vladyslav Shtabovenko"},
  Institutions -> {"FeynCalc project"},
  Emails -> {""},
  Date -> "08.08.2024"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    PropagatorLabel -> "\[Phi]",
    SelfConjugate -> True,
    Indices -> {},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> m }
}


(*        Definitions       *)


m[ ___ ] := m;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] ] == {{I*g*m^2, 0}}

}

