(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"QCD",
  Authors -> {"Vicente V. Figueira"},
  Institutions -> {"QCD"},
  Emails -> {"vfigueira@usp.br"},
  Date -> "02.11.2025"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> A,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0 }
}


(*        Definitions       *)




TheLabel[ V[1, {__}] ] := TheLabel[V[1]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[1, {e1x2}] , V[1, {e2x2}] , V[1, {e3x2}] ] == {{g*FASUNF[e1x2, e2x2, e3x2], 0}, {-(g*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(g*FASUNF[e1x2, e2x2, e3x2]), 0}, {g*FASUNF[e1x2, e2x2, e3x2], 0}, {g*FASUNF[e1x2, e2x2, e3x2], 0}, {-(g*FASUNF[e1x2, e2x2, e3x2]), 0}},

C[ V[1, {e1x2}] , V[1, {e2x2}] , V[1, {e3x2}] , V[1, {e4x2}] ] == {{I*g^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {(-I)*g^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*g^2*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}}

}

