(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Phi^3 + Phi^4 theories",
  Authors -> {"Vladyslav Shtabovenko"},
  Institutions -> {"FeynCalc project"},
  Emails -> {""},
  Date -> "08.08.2024"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    PropagatorLabel -> "\[Phi]",
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Mphi,
    Indices -> {} }
}


(*        Definitions       *)


Mphi[ ___ ] := Mphi;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] ] == {{(-I)*g3*(phi**PRIVATE`crea[phi, {}, 1] - PRIVATE`crea[phi, {}, 1]**phi)*(phi**PRIVATE`crea[phi, {}, 2] - PRIVATE`crea[phi, {}, 2]**phi)*(phi**PRIVATE`crea[phi, {}, 3] - PRIVATE`crea[phi, {}, 3]**phi), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-I)*g4*(phi**PRIVATE`crea[phi, {}, 1] - PRIVATE`crea[phi, {}, 1]**phi)*(phi**PRIVATE`crea[phi, {}, 2] - PRIVATE`crea[phi, {}, 2]**phi)*(phi**PRIVATE`crea[phi, {}, 3] - PRIVATE`crea[phi, {}, 3]**phi)*(phi**PRIVATE`crea[phi, {}, 4] - PRIVATE`crea[phi, {}, 4]**phi), 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
};

